### ISSUE TITLE
Can not use npm multer package in the same time

### ISSUE THREAD

**Issue by AmberYen** [fantasywind/express-route-keeper#1]
as title

const upload = multer({
  dest: UPLOAD_PATH,
});

router.post('/', upload.fields([{
  name: 'media',
  maxCount: 1,
}]), aclObject, handler)

when send a POST request
it will return Cannot POST **PATH**

**Comment by fantasywind** [comment]
Fixed on v0.1.1

Change binding ways to middleware.
